#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export DIRSTACKSIZE=8
setopt autopushd pushdminus pushdsilent pushdtohome

# virtualenvwrapper and pip
case "$OSTYPE" in
  darwin*) OS=mac ;;
  linux*)  OS=linux ;;
  *)       OS=unknown ;;
esac

case "$OS" in
  mac)
    PATH=/Applications/Postgres.app/Contents/Versions/9.4/bin:~/b2g-files/adt-bundle-mac/sdk/platform-tools:~/b2g-files/adt-bundle-mac/sdk/tools:$PATH
    export NODE_PATH="/usr/local/lib/node_modules:${NODE_PATH}"
    fpath=(/usr/local/share/zsh-completions /usr/local/share/zsh/site-functions $fpath)
    export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python
    export NOSE_PROGRESSIVE_EDITOR_SHORTCUT_TEMPLATE='  {dim_format}charm://{path}:{line_number}{normal}{function_format}{hash_if_function}{function}{normal}'
    unalias run-help 2> /dev/null
    autoload run-help
    HELPDIR=/usr/local/share/zsh/helpfiles
    export ARCHFLAGS="-arch x86_64"
    ;;
  linux)
    ;;
esac

export PIP_USE_WHEEL=true
export PIP_WHEEL_DIR=$HOME/.pip/wheels
export PIP_FIND_LINKS=$PIP_WHEEL_DIR
export PROJECTS_HOME=$HOME/Projects
export PROJECT_HOME=$PROJECTS_HOME
export PIP_RESPECT_VIRTUALENV=true
export WORKON_HOME=$HOME/.virtualenvs
export PIP_VIRTUALENV_BASE=$WORKON_HOME
export VIRTUAL_ENV_DISABLE_PROMPT=true
export ADDON_SDK_PATH=$HOME/src/addon-sdk
export GOPATH=$HOME/.golang
export PATH=$PATH:$GOPATH/bin

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
    source /usr/local/bin/virtualenvwrapper.sh
elif [ -f /usr/local/share/python/virtualenvwrapper.sh ]; then
    source /usr/local/share/python/virtualenvwrapper.sh
fi

source ~/.bash_aliases
if [ -f ~/.zsh_local ]; then
    source ~/.zsh_local
fi

eval "$(hub alias -s)"

# added by travis gem
[ -f /Users/pmclanahan/.travis/travis.sh ] && source /Users/pmclanahan/.travis/travis.sh

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

export BYOBU_PREFIX=$(brew --prefix)

if [ -f /usr/local/share/zsh/site-functions/_aws ]; then
    source /usr/local/share/zsh/site-functions/_aws
fi

sha1certcheck() {
  cert_type=$( : | openssl s_client -connect ${1}:443 -ssl3 -cipher 'DES-CBC3-SHA' 2>/dev/null <<< Q | openssl x509 -text | grep 'Signature Algorithm' | cut -d ':' -f 2 | uniq)
  if [ "${cert_type:1}" = "sha1WithRSAEncryption" ]; then
    echo "All's well"
  else
    echo "Bad cert type: $cert_type"
  fi
}
